# Generated by Django 3.0.7 on 2020-08-05 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('avatar', models.ImageField(upload_to='img/users/avatar')),
                ('join_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to='syndication_app.User')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_publisher', to='syndication_app.Community')),
                ('views', models.ManyToManyField(to='syndication_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='admin',
            field=models.ManyToManyField(related_name='community_admin', to='syndication_app.User'),
        ),
        migrations.AddField(
            model_name='community',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_owner', to='syndication_app.User'),
        ),
        migrations.AddField(
            model_name='community',
            name='subscribers',
            field=models.ManyToManyField(related_name='community_subscribers', to='syndication_app.User'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='syndication_app.User')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='syndication_app.Post')),
            ],
        ),
    ]
