# Generated by Django 3.0.7 on 2020-08-06 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndication_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 23, 34, 46, 727923)),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 23, 34, 46, 727013)),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(blank=True, null=True, to='syndication_app.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 23, 34, 46, 701915)),
        ),
    ]
