# Generated by Django 3.0.7 on 2020-08-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndication_app', '0003_auto_20200807_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(blank=True, to='syndication_app.User'),
        ),
    ]
