# Generated by Django 3.0.7 on 2020-08-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndication_app', '0004_auto_20200807_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='img/users/avatar'),
        ),
    ]
