# Generated by Django 3.1 on 2020-08-08 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('blue_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_blue', to=settings.AUTH_USER_MODEL)),
                ('red_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_red', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
