# Generated by Django 3.1 on 2020-08-08 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='blue_user',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='red_user',
        ),
        migrations.CreateModel(
            name='Challenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('R', 'Red'), ('B', 'Blue')], default='R', max_length=1)),
                ('victory', models.BooleanField(default=False)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.battle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='challengers',
            field=models.ManyToManyField(related_name='battles', through='battle.Challenger', to=settings.AUTH_USER_MODEL),
        ),
    ]
