# Generated by Django 3.1 on 2020-08-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_auto_20200808_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='archived',
        ),
        migrations.AddField(
            model_name='battle',
            name='state',
            field=models.CharField(choices=[('W', 'Waiting for Players'), ('E', 'Ready to Start'), ('A', 'Battle in Progress'), ('R', 'Battle Over')], default='W', max_length=1),
        ),
    ]
