# Generated by Django 3.0.8 on 2020-08-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('htmlTitle', models.CharField(max_length=75)),
                ('link', models.CharField(max_length=150)),
                ('snippets', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('results', models.ManyToManyField(related_name='search', to='engine.SearchResult')),
            ],
        ),
    ]
