# Generated by Django 3.0.8 on 2020-08-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rovers", "0005_auto_20200801_1240"),
    ]

    operations = [
        migrations.AddField(
            model_name="rover",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to="profile_pictures"
            ),
        ),
    ]
