# Generated by Django 3.0.8 on 2020-08-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rovers', '0007_auto_20200801_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rover',
            name='username',
            field=models.SlugField(unique=True),
        ),
    ]
