# Generated by Django 3.0.8 on 2020-08-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rovers', '0008_auto_20200805_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rover',
            name='land_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rover',
            name='launch_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rover',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
