# Generated by Django 3.0.8 on 2020-08-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rovers', '0009_auto_20200808_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='rover',
            name='avg_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rover',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rover',
            name='max_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
