# Generated by Django 3.0.8 on 2020-08-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rovers', '0010_auto_20200808_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='rover',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rover',
            name='avg_speed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Feet Per Hour', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rover',
            name='cost',
            field=models.IntegerField(blank=True, help_text='USD', null=True),
        ),
        migrations.AlterField(
            model_name='rover',
            name='max_speed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Feet Per Hour', max_digits=6, null=True),
        ),
    ]
