# Generated by Django 3.0.8 on 2020-08-08 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rovers', '0011_auto_20200808_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rover',
            old_name='avg_speed',
            new_name='average_speed',
        ),
    ]
