# Generated by Django 3.0.8 on 2020-08-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rovers', '0012_auto_20200808_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='rover',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
    ]
