# Generated by Django 3.1 on 2020-08-09 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=280)),
                ('type', models.IntegerField()),
                ('time_date', models.DateField()),
                ('receiver', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='whimsy_messaging_messages_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='whimsy_messaging_messages_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_one', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='whimsy_messaging_conversation_one', to=settings.AUTH_USER_MODEL)),
                ('user_two', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='whimsy_messaging_conversation_two', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
