# Generated by Django 3.0.8 on 2020-08-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
