# Generated by Django 3.0.8 on 2020-08-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
