# Generated by Django 3.0.8 on 2020-08-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundfile',
            name='background_thumbnail',
            field=models.ImageField(default=None, upload_to='backgrounds/'),
        ),
    ]
