# Generated by Django 3.0.8 on 2020-08-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_app', '0002_backgroundfile_background_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundfile',
            name='background_file',
            field=models.FileField(default='defaults/sunrise.jpg', upload_to='backgrounds/'),
        ),
    ]
