# Generated by Django 3.0.8 on 2020-08-02 02:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('hashed_pass', models.CharField(max_length=64)),
                ('identification', models.CharField(default='13ae9d31252f47b7b99870d4d25be9cf', max_length=100)),
                ('nickname', models.CharField(max_length=20)),
                ('bot', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=100)),
                ('identification', models.CharField(default='26b91fcd20d5446c8c027f6850a3c3ce', max_length=100)),
                ('messages', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=2), size=None)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
    ]
