# Generated by Django 3.0.8 on 2020-08-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identification',
            field=models.CharField(default='feea3dac790d4e0886e690e0a051f3e4', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='identification',
            field=models.CharField(default='b57dbe9592c4483d9568780462f6ec13', max_length=100),
        ),
    ]
