# Generated by Django 3.0.8 on 2020-08-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbbackend', '0002_auto_20200802_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identification',
            field=models.CharField(default='483c580b25984d66a160bd62e45daa0c', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='identification',
            field=models.CharField(default='37320c3f0013460d85108e785feeb061', max_length=100),
        ),
    ]
