# Generated by Django 3.0.8 on 2020-08-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbbackend', '0003_auto_20200802_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identification',
            field=models.CharField(default='d018210b096341d9be231b934621eb2f', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='identification',
            field=models.CharField(default='8668a2193abc442ca7cfbd2bedbed770', max_length=100),
        ),
    ]
