# Generated by Django 3.0.8 on 2020-08-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbbackend', '0004_auto_20200802_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identification',
            field=models.CharField(default='11cbc418b0964e12bcc74cbaed9d25a6', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='identification',
            field=models.CharField(default='6190a28c4e9342beaaec6ac252bc63e1', max_length=100),
        ),
    ]
