# Generated by Django 3.0.8 on 2020-08-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbbackend', '0005_auto_20200802_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identification',
            field=models.CharField(default='874e57796770435793bb16a953745010', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='identification',
            field=models.CharField(default='f4604974bd514551b49b9a0d7227588e', max_length=100),
        ),
    ]
