# Generated by Django 3.0.8 on 2020-08-02 03:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbbackend', '0006_auto_20200802_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(default='a3165516bbfe4a77bc29fae2fa8eebec', max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=35)),
                ('comments', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=2), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='identification',
            field=models.CharField(default='f01fe4bd23ed4a3e9128d39938ba8802', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='identification',
            field=models.CharField(default='57f8c8064cc54df1827dce658aa38df5', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='identification',
            field=models.CharField(default='c5928b9fc35b4e12beef01a26c1bb62a', max_length=100),
        ),
    ]
