# Generated by Django 3.0.8 on 2020-08-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbbackend', '0006_auto_20200802_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identification',
            field=models.CharField(default='6b93bbdd056f4eef9d9a9582b626c687', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='identification',
            field=models.CharField(default='623adcd0a6f749b9bac7b464398addab', max_length=100),
        ),
    ]
