# Generated by Django 3.0.8 on 2020-08-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbbackend', '0007_auto_20200802_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identification',
            field=models.CharField(default='7924ddbbb16244d99a8664b6b148bac7', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='identification',
            field=models.CharField(default='fe8acf6fb36c42038fc3cfed7d6a4e9b', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='identification',
            field=models.CharField(default='a0d90167ad9f4527aff2182f6766d472', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='identification',
            field=models.CharField(default='ff17dedb75d54608b11b2d04acd1b690', max_length=100),
        ),
    ]
