# Generated by Django 3.0.8 on 2020-08-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbbackend', '0008_auto_20200802_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identification',
            field=models.CharField(default='62b3cc4e59dd4cdb8168dbcf81dec58b', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='identification',
            field=models.CharField(default='cf74ea63f84743bc82b5b9c51faa50ec', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='identification',
            field=models.CharField(default='a654f81eb1094e0c9c013e2ace1c23df', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='identification',
            field=models.CharField(default='b6504ffe9ccc4f4882d80accb276bf5c', max_length=100),
        ),
    ]
