# Generated by Django 3.0.8 on 2020-08-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbbackend', '0010_auto_20200803_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
