# Generated by Django 3.0.8 on 2020-08-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbbackend', '0011_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='session_id',
            field=models.CharField(default='dbc95c3998c34f0b90838e717611fb0d', max_length=100),
        ),
    ]
