# Generated by Django 3.0.8 on 2020-08-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_songfile',
            field=models.FileField(upload_to='songs'),
        ),
    ]
