# Generated by Django 3.0.8 on 2020-08-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0002_auto_20200802_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_duration',
        ),
    ]
