# Generated by Django 3.0.8 on 2020-08-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post_date_published',
            new_name='post_date_posted',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='post_last_edited',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='post_title',
        ),
    ]
