# Generated by Django 3.1 on 2020-08-08 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 13, 14, 51, 737848, tzinfo=utc)),
        ),
    ]
