# Generated by Django 3.1 on 2020-08-08 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200808_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 16, 55, 9, 858778, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
