# Generated by Django 3.1 on 2020-08-09 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200809_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 14, 39, 49, 336121, tzinfo=utc)),
        ),
    ]
