# Generated by Django 3.0.9 on 2020-08-05 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_delete_page'),
        ('user_media', '0002_auto_20200803_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='filename',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_media.Media'),
        ),
        migrations.AddField(
            model_name='media',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
    ]
