# Generated by Django 3.1 on 2020-08-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_media', '0003_folders_squashed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='media',
            name='site',
        ),
    ]
