# Generated by Django 3.1 on 2020-08-08 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0006_folder_filename'),
        ('user_media', '0004_auto_20200807_0036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='Image',
        ),
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('folder', 'filename')},
        ),
    ]
