# Generated by Django 3.0.9 on 2020-08-05 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0009_remove_folder_filename'),
        ('user_media', '0010_auto_20200805_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='folder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='folders.Folder'),
            preserve_default=False,
        ),
    ]
