# Generated by Django 3.0.8 on 2020-08-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagepost",
            name="image_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imagepost", name="sol", field=models.IntegerField(default=0),
        ),
    ]
