# Generated by Django 3.0.8 on 2020-08-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200805_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image_id',
            field=models.IntegerField(blank=True, default=0, help_text="NASA's image ID associated with the photo.", null=True),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='sol',
            field=models.IntegerField(default=0, help_text="Number of Mars-days since the rover's landing."),
        ),
    ]
