# Generated by Django 3.0.8 on 2020-08-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=256)),
                ('author', models.CharField(default='unknown', max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
