# Generated by Django 3.0.9 on 2020-08-05 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('folders', '0001_initial'), ('folders', '0002_remove_folder_home_group'), ('folders', '0003_auto_20200805_0150'), ('folders', '0004_auto_20200805_0151'), ('folders', '0005_auto_20200805_0153'), ('folders', '0006_auto_20200805_0154'), ('folders', '0007_auto_20200805_0154'), ('folders', '0008_auto_20200805_0157'), ('folders', '0009_remove_folder_filename')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0005_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.Folder')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
