# Generated by Django 3.0.9 on 2020-08-05 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='home_group',
        ),
    ]
