# Generated by Django 3.1 on 2020-08-07 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_auto_20200807_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='directory',
            new_name='path',
        ),
    ]
