# Generated by Django 3.1 on 2020-08-07 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_auto_20200807_0242'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folderref',
            unique_together={('folder', 'filename')},
        ),
    ]
