# Generated by Django 3.1 on 2020-08-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_auto_20200807_0522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FolderRef',
        ),
    ]
