# Generated by Django 3.1 on 2020-08-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0005_delete_folderref'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='filename',
            field=models.CharField(default='/', max_length=256),
            preserve_default=False,
        ),
    ]
