# Generated by Django 3.0.9 on 2020-08-05 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0008_auto_20200805_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='filename',
        ),
    ]
