# Generated by Django 3.0.8 on 2020-08-02 23:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20200802_2117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Texts',
        ),
    ]
