# Generated by Django 3.0.8 on 2020-08-03 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20200802_2302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Texts',
            new_name='Text',
        ),
    ]
