# Generated by Django 3.0.8 on 2020-08-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default='Hi, I am a HoneyFeed User', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='profile_imgs/'),
        ),
    ]
