# Generated by Django 3.0.8 on 2020-08-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='thread_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
