# Generated by Django 3.0.8 on 2020-08-03 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200803_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True, unique=True),
        ),
    ]
