# Generated by Django 3.0.8 on 2020-08-06 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200806_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downvoted_by',
            field=models.ManyToManyField(related_name='comment_downvoted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='comment_upvoted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
