# Generated by Django 3.0.9 on 2020-08-05 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(default=0,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='gifapp.ProjectType'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='project_type',
            field=models.CharField(choices=[('GF', 'gif project'), ('IG', 'image project')], max_length=25),
        ),
    ]
