# Generated by Django 3.0.9 on 2020-08-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifapp', '0005_auto_20200806_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='preview_version',
        ),
    ]
