# Generated by Django 3.0.9 on 2020-08-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifapp', '0007_auto_20200806_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['animation_position']},
        ),
        migrations.AddField(
            model_name='project',
            name='preview_version',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_data',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='upload_version',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
