# Generated by Django 3.1 on 2020-08-08 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifapp', '0007_auto_20200806_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['animation_position']},
        ),
    ]
