# Generated by Django 3.0.9 on 2020-08-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifapp', '0008_auto_20200808_1248'),
        ('gifapp', '0008_auto_20200808_0407'),
    ]

    operations = [
    ]
