# Generated by Django 3.0.9 on 2020-08-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifapp', '0009_merge_20200808_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='preview_version',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='upload_version',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
