# Generated by Django 3.0.9 on 2020-08-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifapp', '0011_remove_comment_parent_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_created']},
        ),
    ]
