# Generated by Django 3.0.9 on 2020-08-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifapp', '0012_auto_20200809_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
    ]
