# Generated by Django 3.0.8 on 2020-08-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20200809_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='', upload_to='post_images'),
            preserve_default=False,
        ),
    ]
