# Generated by Django 3.0.8 on 2020-08-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20200808_2231'),
        ('feed', '0005_auto_20200809_0341'),
    ]

    operations = [
    ]
