# Generated by Django 3.0.8 on 2020-08-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('feed', '0006_auto_20200809_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
