# Generated by Django 3.0.8 on 2020-08-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20200809_1106'),
        ('feed', '0006_merge_20200809_1117'),
    ]

    operations = [
    ]
