# Generated by Django 3.0.8 on 2020-08-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_merge_20200809_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='', upload_to='post_images'),
            preserve_default=False,
        ),
    ]
