# Generated by Django 3.0.8 on 2020-08-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wired_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article", name="slug", field=models.SlugField(unique=True),
        ),
    ]
