# Generated by Django 3.0.8 on 2020-08-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wired_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article", name="publication_date", field=models.DateField(),
        ),
    ]
