# Generated by Django 3.0.8 on 2020-08-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wired_app", "0002_auto_20200805_2125"),
        ("wired_app", "0002_auto_20200806_1621"),
    ]

    operations = []
