# Generated by Django 3.0.8 on 2020-08-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wired_app', '0005_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('business', 'Business'), ('culture', 'Culture'), ('politics', 'Politics'), ('general', 'General News')], default='technology', max_length=25),
        ),
    ]
