# Generated by Django 3.0.7 on 2020-08-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irc_chat', '0002_message_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.TextField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
