# Generated by Django 3.0.8 on 2020-08-01 12:33

import django.utils.timezone
import page_maker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('style_sheet', models.FileField(upload_to='styles/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('votes', models.IntegerField(default=0)),
                ('user_title', models.CharField(max_length=100)),
                ('user_text_1', models.TextField(verbose_name='subtitle paragraph')),
                ('user_text_2', models.TextField(verbose_name='main body paragraph')),
                ('user_text_3', models.TextField(verbose_name='closing paragraph')),
                ('user_image_1', models.ImageField(blank=True, null=True,
                                                   upload_to=page_maker.models.get_user_dir_path,
                                                   verbose_name='background image')),
                ('user_image_2', models.ImageField(blank=True, null=True,
                                                   upload_to=page_maker.models.get_user_dir_path,
                                                   verbose_name='header image')),
                ('user_image_3', models.ImageField(blank=True, null=True,
                                                   upload_to=page_maker.models.get_user_dir_path,
                                                   verbose_name='main image')),
                ('user_image_4', models.ImageField(blank=True, null=True,
                                                   upload_to=page_maker.models.get_user_dir_path,
                                                   verbose_name='footer image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             to=settings.AUTH_USER_MODEL)),
                ('template_used', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                                    to='page_maker.Template')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=500)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             to=settings.AUTH_USER_MODEL)),
                ('parent_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  to='page_maker.Webpage')),
            ],
        ),
    ]
