# Generated by Django 3.0.9 on 2020-08-03 15:27

import django.core.validators
import django.utils.timezone
import page_maker.models
import relativefilepathfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('style_sheet',
                 relativefilepathfield.fields.RelativeFilePathField(match='.*\\.css$',
                                                                    path=page_maker.models.get_theme_path,
                                                                    recursive=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('thumbnail',
                 models.ImageField(blank=True, default=None, null=True, upload_to='thumbnails/',
                                   validators=[
                                       django.core.validators.validate_image_file_extension])),
                ('votes', models.IntegerField(default=0)),
                ('user_title', models.CharField(max_length=100, verbose_name='page title')),
                ('user_text_1', models.TextField(verbose_name='subtitle paragraph')),
                ('user_text_2', models.TextField(verbose_name='main body paragraph')),
                ('user_text_3', models.TextField(verbose_name='closing paragraph')),
                ('user_image_1', models.ImageField(blank=True, max_length=200, null=True,
                                                   upload_to=page_maker.models.get_user_dir_path,
                                                   validators=[
                                                       django.core.validators.validate_image_file_extension],
                                                   verbose_name='header image')),
                ('user_image_2', models.ImageField(blank=True, max_length=200, null=True,
                                                   upload_to=page_maker.models.get_user_dir_path,
                                                   validators=[
                                                       django.core.validators.validate_image_file_extension],
                                                   verbose_name='main image')),
                ('user_image_3', models.ImageField(blank=True, max_length=200, null=True,
                                                   upload_to=page_maker.models.get_user_dir_path,
                                                   validators=[
                                                       django.core.validators.validate_image_file_extension],
                                                   verbose_name='footer image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             to=settings.AUTH_USER_MODEL)),
                ('template_used', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                                                    to='page_maker.Template')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=500)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             to=settings.AUTH_USER_MODEL)),
                ('parent_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  to='page_maker.Webpage')),
            ],
        ),
    ]
