# Generated by Django 3.0.8 on 2020-08-01 19:29

import django.core.validators
import page_maker.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('page_maker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='style_sheet',
            field=models.FilePathField(choices=[('TEMP', 'TEMP')]),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='thumbnails/',
                                    validators=[
                                        django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='user_image_1',
            field=models.ImageField(blank=True, null=True,
                                    upload_to=page_maker.models.get_user_dir_path, validators=[
                    django.core.validators.validate_image_file_extension],
                                    verbose_name='background image'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='user_image_2',
            field=models.ImageField(blank=True, null=True,
                                    upload_to=page_maker.models.get_user_dir_path, validators=[
                    django.core.validators.validate_image_file_extension],
                                    verbose_name='header image'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='user_image_3',
            field=models.ImageField(blank=True, null=True,
                                    upload_to=page_maker.models.get_user_dir_path, validators=[
                    django.core.validators.validate_image_file_extension],
                                    verbose_name='main image'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='user_image_4',
            field=models.ImageField(blank=True, null=True,
                                    upload_to=page_maker.models.get_user_dir_path, validators=[
                    django.core.validators.validate_image_file_extension],
                                    verbose_name='footer image'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='user_title',
            field=models.CharField(max_length=100, verbose_name='page title'),
        ),
    ]
