# Generated by Django 3.1 on 2020-08-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_maker', '0002_auto_20200801_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='style_sheet',
            field=models.FileField(upload_to='styles/'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
