# Generated by Django 3.0.8 on 2020-08-09 05:20

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(validators=[users.validators.valid_age_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default_pfp.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_css',
            field=models.TextField(blank=True, max_length=10000, validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
    ]
