# Generated by Django 3.0.8 on 2020-08-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200809_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_css',
            new_name='custom_css',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='place',
        ),
    ]
