# Generated by Django 3.0.9 on 2020-08-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earlcal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
