# Generated by Django 3.0.8 on 2020-08-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('snippet', models.TextField()),
                ('display_link', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
    ]
