# Generated by Django 3.0.8 on 2020-08-07 18:13

from django.db import migrations, models
import pandas as pd
def load_data(apps, schema_editor):
    data = pd.read_csv('search/search_data/recipes_serp_data.csv')
    Result = apps.get_model("search", "Result")
    for i in range(0, data.shape[0]):
        new_result = Result(title=data.title[i], snippet = data.snippet[i],display_link = data.displayLink[i], link = data.link[i])
        new_result.save()

class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
