# Generated by Django 3.0.8 on 2020-08-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.AddField(model_name="profile", name="status", field=models.CharField(default=":-)", max_length=100))
    ]
