# Generated by Django 3.0.8 on 2020-08-09 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("chat", "0004_message_text"), ("users", "0003_auto_20200803_2022")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_visited",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="chat.Room"
            ),
        )
    ]
