# Generated by Django 3.0.8 on 2020-08-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0003_auto_20200803_2022")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="background",
            field=models.ImageField(default="default.jpg", upload_to="background"),
        )
    ]
