# Generated by Django 3.0.8 on 2020-08-09 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("chat", "0004_message_text"), ("users", "0004_profile_last_visited")]

    operations = [
        migrations.RemoveField(model_name="profile", name="last_visited"),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "chat_room",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="chat.Room"
                    ),
                ),
                ("history", models.ManyToManyField(to="users.Profile")),
            ],
        ),
    ]
