# Generated by Django 3.0.8 on 2020-08-09 03:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("chat", "0004_message_text"), ("users", "0005_auto_20200808_2127")]

    operations = [
        migrations.CreateModel(
            name="ChatRoomVisit",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time_visited", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "chat_room",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="chat.Room"
                    ),
                ),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.Profile")),
            ],
        ),
        migrations.DeleteModel(name="ChatRoom"),
    ]
