# Generated by Django 3.0.8 on 2020-08-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0006_auto_20200807_1748")]

    operations = [
        migrations.AlterField(model_name="profile", name="background", field=models.ImageField(upload_to="background"))
    ]
