# Generated by Django 3.0.8 on 2020-08-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0006_auto_20200808_2211"), ("users", "0007_auto_20200808_2030")]

    operations = []
