# Generated by Django 3.0.8 on 2020-08-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ticker_symbol', models.CharField(max_length=4)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
