# Generated by Django 3.0.8 on 2020-08-04 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='current_price',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='last_price',
            new_name='high',
        ),
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='low',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='open',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker_symbol',
            field=models.CharField(max_length=5),
        ),
    ]
