# Generated by Django 3.0.8 on 2020-08-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20200803_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='close',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='high',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
