# Generated by Django 3.0.8 on 2020-08-07 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsFeed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("location", models.CharField(max_length=50, verbose_name="Location")),
                (
                    "date_published",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date Published"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
            ],
        ),
    ]
