# Generated by Django 3.0.8 on 2020-08-08 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_newsfeed"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="date_listed",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Time and date listed"
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="date_traded",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Time and date of trade"
            ),
        ),
    ]
