# Generated by Django 3.0.8 on 2020-08-09 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_homepage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing", old_name="silver_per_unit", new_name="silver_price",
        ),
        migrations.RemoveField(model_name="listing", name="barter_qty_per_unit",),
        migrations.AddField(
            model_name="listing",
            name="barter_product_quantity",
            field=models.IntegerField(null=True, verbose_name="Barter quantity"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.InventoryRecord",
                verbose_name="Listed Item",
            ),
        ),
    ]
