# Generated by Django 3.0.9 on 2020-08-05 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('pages', '0001_initial'), ('pages', '0002_auto_20200805_0150'), ('pages', '0003_auto_20200805_0151'), ('pages', '0004_auto_20200805_0153'), ('pages', '0005_auto_20200805_0154'), ('pages', '0006_auto_20200805_0154'), ('pages', '0007_auto_20200805_0157'), ('pages', '0008_auto_20200805_0217'), ('pages', '0009_auto_20200805_0221'), ('pages', '0010_auto_20200805_0228'), ('pages', '0011_auto_20200805_0231')]

    initial = True

    dependencies = [
        ('folders', '0009_remove_folder_filename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0005_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('version', models.CharField(choices=[('H1', 'HTML 1'), ('H2', 'HTML 2')], default='H1', max_length=2)),
                ('content', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folders.Folder')),
            ],
            options={
                'verbose_name_plural': 'pages',
                'unique_together': {('site', 'filename')},
            },
        ),
    ]
