# Generated by Django 3.1 on 2020-08-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_auto_20200807_0036'),
        ('pages', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('folder', 'filename')},
        ),
        migrations.RemoveField(
            model_name='page',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='page',
            name='site',
        ),
    ]
