# Generated by Django 3.1 on 2020-08-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="file_name",
            field=models.CharField(default="index.html", max_length=256),
            preserve_default=False,
        ),
    ]
