# Generated by Django 3.0.9 on 2020-08-05 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0009_remove_folder_filename'),
        ('pages', '0007_auto_20200805_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='parent',
        ),
        migrations.AddField(
            model_name='page',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.Folder'),
        ),
    ]
