# Generated by Django 3.0.9 on 2020-08-05 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200805_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page'),
        ),
    ]
