# Generated by Django 3.0.8 on 2020-08-08 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200807_0305'),
        ('chat', '0002_auto_20200807_1200'),
    ]

    operations = [
    ]
