# Generated by Django 3.0.8 on 2020-08-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200804_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='replied_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_agent',
        ),
    ]
