# Generated by Django 3.0.8 on 2020-08-08 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='day',
            field=models.DateField(default=datetime.date(2020, 8, 8)),
        ),
    ]
