# Generated by Django 3.0.8 on 2020-08-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20200808_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='latitude',
            field=models.FloatField(default=46.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='longitude',
            field=models.FloatField(default=46.5),
            preserve_default=False,
        ),
    ]
