#!/bin/sh

cd acceptable-albatrosses

echo "Checking for Python syntax errors or undefined names with flake8..."
pipenv run flake8 albatrosses_hub --count --select=E9,F63,F7,F82 --show-source --statistics
echo ""

echo "Checking other style errors with flake8..."
pipenv run flake8 albatrosses_hub --count --statistics
echo ""

echo "Checking static typing with mypy..."
cd albatrosses_hub
pipenv run mypy . --config-file ../mypy.ini
cd ..
echo ""

echo "Checking Python and style errors with pylint..."
pipenv run pylint albatrosses_hub/**/*.py
echo ""

echo "Checking formatted code with black..."
pipenv run black albatrosses_hub --check -l 119 --exclude migrations
echo ""
