# Generated by Django 3.0.8 on 2020-08-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('html_url', models.CharField(max_length=100)),
                ('coat_of_arms', models.CharField(max_length=100)),
                ('long_bio', models.TextField()),
            ],
        ),
    ]
