# Generated by Django 3.0.8 on 2020-08-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earls', '0002_auto_20200808_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='passport_id',
            field=models.CharField(default=1234567, max_length=15),
            preserve_default=False,
        ),
    ]
