# Generated by Django 3.0.8 on 2020-08-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_auto_20200805_1725"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post", options={"ordering": ("author__username",)},
        ),
    ]
