# Generated by Django 3.0.8 on 2020-08-08 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_auto_20200807_1709"),
        ("blogs", "0003_auto_20200806_2327"),
    ]

    operations = []
