# Generated by Django 3.0.8 on 2020-08-09 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogs", "0006_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                related_name="blog_posts_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(name="Like",),
    ]
