# Generated by Django 3.0.8 on 2020-08-08 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaquiz',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
