# Generated by Django 3.0.8 on 2020-08-03 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaquiz',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
