# Generated by Django 3.0.8 on 2020-08-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_builder', '0002_triviaquiz_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaquestion',
            name='question_answer',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='question_text',
            field=models.CharField(max_length=1000),
        ),
    ]
