# Generated by Django 3.0.7 on 2020-08-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20200801_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='document',
        ),
    ]
