# Generated by Django 3.0.8 on 2020-08-08 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20200807_2246"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="searches_made",),
    ]
