# Generated by Django 3.0.8 on 2020-08-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_account_is_active"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="is_active",),
    ]
