# Generated by Django 3.0.8 on 2020-08-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guestbook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestbook",
            name="author",
            field=models.CharField(max_length=100),
        ),
    ]
