# Generated by Django 3.0.9 on 2020-08-03 21:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='key',
            field=models.ForeignKey(default=datetime.datetime(2020, 8, 3, 21, 57, 9, 484273, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='guestbook.Guestbook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='author',
            field=models.TextField(),
        ),
    ]
