# Generated by Django 3.0.9 on 2020-08-03 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guestbook', '0002_auto_20200803_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
