# Generated by Django 3.0.9 on 2020-08-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_auto_20200803_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='page',
            field=models.TextField(default='home'),
        ),
    ]
