# Generated by Django 3.0.8 on 2020-08-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_guestbook_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestbook',
            name='page',
        ),
    ]
