# Generated by Django 3.0.9 on 2020-08-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0004_auto_20200803_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='author',
            field=models.TextField(),
        ),
    ]
