# Generated by Django 3.1 on 2020-08-04 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0002_auto_20200804_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonuser',
            name='nickname',
            field=models.CharField(default='nerdy-vermilion-frise', max_length=25),
        ),
        migrations.AlterField(
            model_name='anonuser',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
