# Generated by Django 3.1 on 2020-08-05 00:13

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0003_auto_20200804_2322'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='anonuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='anonuser',
            name='nickname',
            field=models.CharField(default='clammy-beige-fowl', max_length=25),
        ),
    ]
