# Generated by Django 3.1 on 2020-08-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0004_auto_20200805_0013'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='anonuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='anonuser',
            name='nickname',
            field=models.CharField(default='randy-cinnamon-dragon', max_length=25),
        ),
    ]
