# Generated by Django 3.1 on 2020-08-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0005_auto_20200805_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonuser',
            name='nickname',
            field=models.CharField(default='cloudy-thistle-javanese', max_length=25),
        ),
    ]
