# Generated by Django 3.0.8 on 2020-08-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0006_auto_20200805_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonuser',
            name='nickname',
            field=models.CharField(default='lovely-azure-gar', max_length=25),
        ),
    ]
