# Generated by Django 3.1 on 2020-08-09 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0007_auto_20200807_2303'),
        ('anon', '0002_auto_20200804_1744'),
    ]

    operations = [
    ]
