# Generated by Django 3.1 on 2020-08-09 13:21

from django.db import migrations, models
import django.utils.timezone
import namegenerator


class Migration(migrations.Migration):

    dependencies = [
        ('anon', '0008_merge_20200809_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonuser',
            name='auth_expiration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='anonuser',
            name='auth_token',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='anonuser',
            name='nickname',
            field=models.CharField(default=namegenerator.gen, max_length=25),
        ),
    ]
