# Generated by Django 3.0.8 on 2020-08-03 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_preference', models.CharField(choices=[('COLD', 'I tend to be cold!'), ('NORM', 'Normal'), ('WARM', 'Warm, I am on fire!')], default='NORM', max_length=4)),
                ('name_preference', models.CharField(max_length=20)),
                ('display_weather', models.BooleanField(default=True)),
                ('display_news', models.BooleanField(default=True)),
                ('display_music', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
