# Generated by Django 3.0.8 on 2020-08-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background_image',
            field=models.FileField(default='defaults/sunrise.jpg', upload_to='backgrounds/'),
        ),
    ]
