# Generated by Django 3.0.8 on 2020-08-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('users', '0002_auto_20200807_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='city_name',
            field=models.CharField(default='London', max_length=25),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='country_name',
            field=models.CharField(default='UK', max_length=25),
        ),
    ]
