# Generated by Django 3.0.8 on 2020-08-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_news', '0003_auto_20200808_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
