# Generated by Django 3.0.8 on 2020-08-09 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retro_news', '0005_articlecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='retro_news.BlogArticle'),
        ),
    ]
