from django.urls import path
from . import views

urlpatterns = [
    path(
        "",
        views.home,
        name="forum-homepage"
    ),
    path(
        'forum/threads',
        views.threads,
        name="threads-all"
    ),
    path(
      'forum/threads/<int:id>',
      views.threads,
      name='threads-single'
    ),
    path(
        'forum/threads/new',
        views.NewThread.as_view(),
        name="new-thread"
    ),
    path(
        'forum/threads/<int:id>/edit',
        views.EditThread.as_view(),
        name="edit-thread"
    ),
    path(
        'forum/threads/<int:id>/delete',
        views.DeleteThread.as_view(),
        name="delete-thread"
    ),
    path(
        'forum/threads/<int:id>/new',
        views.NewMessage.as_view(),
        name="new-message"
    ),
    path(
        'forum/threads/<int:id>/<int:msg_id>/edit',
        views.EditMessage.as_view(),
        name="edit-message"
    ),
    path(
        'forum/threads/<int:id>/<int:msg_id>/delete',
        views.DeleteMessage.as_view(),
        name="delete-message"
    ),
]
