# Generated by Django 3.0.8 on 2020-08-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='recipent',
        ),
    ]
