# Generated by Django 2.2.6 on 2020-08-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retroNet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
