# Generated by Django 3.0.8 on 2020-08-03 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("chat", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="message", name="timestamp", field=models.DateTimeField(default=django.utils.timezone.now)
        )
    ]
