# Generated by Django 3.0.8 on 2020-08-03 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("chat", "0002_message_timestamp")]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="room_member",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chat.RoomMember"),
        )
    ]
