# Generated by Django 3.0.8 on 2020-08-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chat", "0003_auto_20200803_0110")]

    operations = [
        migrations.AddField(
            model_name="message",
            name="text",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        )
    ]
