# Generated by Django 3.0.8 on 2020-08-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chat", "0004_message_text")]

    operations = [
        migrations.AddField(model_name="roommember", name="active", field=models.BooleanField(default=False))
    ]
