# Generated by Django 3.0.8 on 2020-08-06 01:09

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_auto_20200805_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBlueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sell_price', models.BigIntegerField()),
                ('buy_price', models.BigIntegerField()),
                ('item_uses', models.BigIntegerField()),
                ('consumable', models.BooleanField()),
                ('item_function', models.TextField()),
                ('item_kwargs', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_uses', models.BigIntegerField()),
                ('equipped', models.BooleanField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.ItemBlueprint')),
                ('user_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
    ]
