# Generated by Django 3.0.3 on 2020-08-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200806_2017'),
        ('game', '0003_itemblueprint_itemownership'),
    ]

    operations = [
    ]
