# Generated by Django 3.0.8 on 2020-08-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200808_2129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
