# Generated by Django 3.1 on 2020-08-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=24)),
                ('points', models.IntegerField(default=0)),
                ('session_code', models.CharField(max_length=6)),
                ('answered_this_round', models.BooleanField(default=False)),
            ],
        ),
    ]
