# Generated by Django 3.0.8 on 2020-08-05 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmachine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floppy',
            name='vm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vmachine.VMachine'),
        ),
    ]
