# Generated by Django 3.0.8 on 2020-08-05 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmachine', '0002_floppy_vm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floppy',
            name='vm',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vmachine.VMachine'),
        ),
    ]
