# Generated by Django 3.0.8 on 2020-08-05 16:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmachine', '0005_auto_20200805_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmachine',
            name='floppy_disks_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='vmachine',
            name='floppy_disks_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, null=True), null=True, size=None),
        ),
    ]
