# Generated by Django 3.0.8 on 2020-08-05 16:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmachine', '0006_auto_20200805_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floppy',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='floppy',
            name='storage_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vmachine',
            name='floppy_disks_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30, null=True), null=True, size=None),
        ),
    ]
