# Generated by Django 3.0.8 on 2020-08-06 13:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmachine', '0008_auto_20200805_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floppy',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='vmachine',
            name='floppy_disks_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30, null=True), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='vmachine',
            name='floppy_disks_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300, null=True), default=list, null=True, size=None),
        ),
    ]
