# Generated by Django 3.0.8 on 2020-08-09 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailmessages', '0002_auto_20200809_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    to_field='username'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user',
                                    to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
