# Generated by Django 3.0.8 on 2020-08-09 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200809_0341'),
        ('users', '0002_auto_20200808_2354'),
    ]

    operations = [
    ]
