# Generated by Django 3.0.8 on 2020-08-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200809_1517'),
        ('users', '0004_auto_20200809_1929'),
    ]

    operations = [
    ]
