# Generated by Django 3.0.8 on 2020-08-05 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trivia_builder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveTriviaQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(default='UCTZY5', editable=False, max_length=6, unique=True)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('players', models.ManyToManyField(related_name='quiz_players', to='trivia_runner.Player')),
                ('session_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_master', to=settings.AUTH_USER_MODEL)),
                ('trivia_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_builder.TriviaQuiz')),
            ],
        ),
    ]
