
# Generated by Django 3.0.8 on 2020-08-03 05:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trivia_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTriviaQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(6)])),
                ('current_question_index', models.PositiveIntegerField()),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('players', models.ManyToManyField(related_name='quiz_players', to=settings.AUTH_USER_MODEL)),
                ('session_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_master', to=settings.AUTH_USER_MODEL)),
                ('trivia_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_builder.TriviaQuiz')),
            ],
        ),
    ]
