# Generated by Django 3.1 on 2020-08-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_runner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetriviaquiz',
            name='session_code',
            field=models.CharField(default='EPSY6X', editable=False, max_length=6, unique=True),
        ),
    ]
