# Generated by Django 3.0.8 on 2020-08-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_runner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetriviaquiz',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activetriviaquiz',
            name='session_code',
            field=models.CharField(default='VX76WX', editable=False, max_length=6, unique=True),
        ),
    ]
