# Generated by Django 3.1 on 2020-08-09 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_builder', '0001_initial'),
        ('trivia_runner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=500)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_runner.player')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_builder.triviaquestion')),
            ],
        ),
    ]
