# Generated by Django 3.0.8 on 2020-08-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_runner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('number', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='activetriviaquiz',
            name='players',
            field=models.ManyToManyField(related_name='quiz_players', to='trivia_runner.Player'),
        ),
    ]
