# Generated by Django 3.1 on 2020-08-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_runner', '0002_auto_20200808_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetriviaquiz',
            name='session_code',
            field=models.CharField(default='4T34OH', editable=False, max_length=6, unique=True),
        ),
    ]
