# Generated by Django 3.0.8 on 2020-08-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_runner', '0002_auto_20200806_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetriviaquiz',
            name='session_code',
            field=models.CharField(default='E5QYHU', editable=False, max_length=6, unique=True),
        ),
    ]
