# Generated by Django 3.1 on 2020-08-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_runner', '0002_auto_20200807_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team_name',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='activetriviaquiz',
            name='session_code',
            field=models.CharField(default='GNCP3J', editable=False, max_length=6, unique=True),
        ),
    ]
