# Generated by Django 3.0.8 on 2020-08-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_runner', '0003_auto_20200807_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetriviaquiz',
            name='session_code',
            field=models.CharField(default='SQ5HEV', editable=False, max_length=6, unique=True),
        ),
    ]
