# Generated by Django 3.0.9 on 2020-08-05 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_site_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
