# Generated by Django 3.0.8 on 2020-08-02 19:17

from django.db import migrations
import enum_field


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200802_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userthreadevent',
            name='type',
            field=enum_field.EnumField(enum_field.Enum(('create-message', 'CREATE'), ('view-thread', 'VIEW')), choices=[]),
        ),
    ]
