# Generated by Django 3.0.8 on 2020-08-02 22:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200802_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 22, 25, 7, 120447, tzinfo=utc)),
        ),
    ]
