# Generated by Django 3.0.8 on 2020-08-03 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0005_auto_20200802_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_edited',
            field=models.DateTimeField(default=models.DateTimeField(default=django.utils.timezone.now)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userthreadevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
