# Generated by Django 3.0.8 on 2020-08-03 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20200803_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
