# Generated by Django 3.0.8 on 2020-08-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_thread_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
