# Generated by Django 3.0.8 on 2020-08-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_thread_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserThreadEvent',
        ),
    ]
