# Generated by Django 3.0.8 on 2020-08-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='z',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='z',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
