# Generated by Django 3.1 on 2020-08-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MUD', '0002_auto_20200808_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
