# Generated by Django 3.0.8 on 2020-08-04 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MUD', '0002_auto_20200801_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='x',
        ),
        migrations.RemoveField(
            model_name='player',
            name='y',
        ),
        migrations.RemoveField(
            model_name='player',
            name='z',
        ),
        migrations.RemoveField(
            model_name='room',
            name='x',
        ),
        migrations.RemoveField(
            model_name='room',
            name='y',
        ),
        migrations.RemoveField(
            model_name='room',
            name='z',
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MUD.Room'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='connections',
            field=models.ManyToManyField(blank=True, related_name='_room_connections_+', to='MUD.Room'),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Room', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(max_length=512),
        ),
    ]
