# Generated by Django 3.0.8 on 2020-08-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='start_date',
            new_name='created_date',
        ),
    ]
