# Generated by Django 3.0.8 on 2020-08-02 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_auto_20200801_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadmessage',
            name='user',
            field=models.ForeignKey(on_delete=models.SET('Deleted'), to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
