# Generated by Django 3.0.8 on 2020-08-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200804_0537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='user',
            new_name='created_by',
        ),
    ]
