# Generated by Django 3.0.8 on 2020-08-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20200802_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadmessage',
            name='username',
        ),
    ]
