# Generated by Django 3.0.8 on 2020-08-06 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0004_auto_20200804_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET('Deleted'), to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
