# Generated by Django 3.0.8 on 2020-08-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20200806_0544'),
        ('forum', '0005_auto_20200806_1208'),
    ]

    operations = [
    ]
