# Generated by Django 3.0.8 on 2020-08-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20200802_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threadmessage',
            old_name='user_id',
            new_name='user',
        ),
    ]
