# Generated by Django 3.0.8 on 2020-08-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_merge_20200807_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadmessage',
            name='message',
            field=models.TextField(max_length=3000),
        ),
    ]
