# Generated by Django 3.0.8 on 2020-08-09 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('tab_one', models.CharField(blank=True, default='', max_length=200)),
                ('tab_two', models.CharField(blank=True, default='', max_length=200)),
                ('tab_three', models.CharField(blank=True, default='', max_length=200)),
                ('multitab_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
    ]
