# Generated by Django 3.0.8 on 2020-08-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.TextField()),
                ('nickname', models.TextField(default=models.TextField())),
                ('avatar', models.URLField()),
                ('acc_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_exp_date', models.DateTimeField()),
                ('discord_id', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='OurUser',
        ),
    ]
