# Generated by Django 3.0.8 on 2020-08-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200802_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='token_exp_date',
            field=models.DateTimeField(null=True),
        ),
    ]
