# Generated by Django 3.0.8 on 2020-08-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200802_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='nickname',
            field=models.TextField(default='<django.db.models.fields.TextField>'),
        ),
    ]
