# Generated by Django 3.0.8 on 2020-08-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200804_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumuser',
            name='acc_token',
        ),
        migrations.RemoveField(
            model_name='forumuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='forumuser',
            name='discord_id',
        ),
        migrations.RemoveField(
            model_name='forumuser',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='forumuser',
            name='token_exp_date',
        ),
    ]
