# Generated by Django 3.0.8 on 2020-08-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200808_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='nickname',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
