# Generated by Django 3.0.8 on 2020-08-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_youtube', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
