# Generated by Django 3.0.8 on 2020-08-02 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_youtube', '0002_auto_20200802_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 23, 57, 34, 15517)),
        ),
    ]
