# Generated by Django 3.0.8 on 2020-08-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200, null=True)),
                ('img', models.ImageField(null=True, upload_to='static/user_pixel')),
                ('greeting', models.CharField(default='Greeting', max_length=200, null=True)),
                ('activity', models.CharField(default='Activity', max_length=200, null=True)),
                ('adjective1', models.CharField(default='Adjective', max_length=200, null=True)),
                ('verb0', models.CharField(default='Verb', max_length=200, null=True)),
                ('direction', models.CharField(default='Direction', max_length=200, null=True)),
                ('pastverb', models.CharField(default='Pastverb', max_length=200, null=True)),
                ('noun1', models.CharField(default='Noun', max_length=200, null=True)),
                ('adjective2', models.CharField(default='Adjective', max_length=200, null=True)),
                ('verb1', models.CharField(default='Verb', max_length=200, null=True)),
                ('noun2', models.CharField(default='Noun', max_length=200, null=True)),
                ('verb2', models.CharField(default='Verb', max_length=200, null=True)),
                ('noun3', models.CharField(default='Noun', max_length=200, null=True)),
                ('noun4', models.CharField(default='Noun', max_length=200, null=True)),
                ('verb3', models.CharField(default='Verb', max_length=200, null=True)),
                ('noun5', models.CharField(default='Pluralnoun', max_length=200, null=True)),
                ('noun6', models.CharField(default='Pluralnoun', max_length=200, null=True)),
                ('exclamation', models.CharField(default='Exclamation', max_length=200, null=True)),
                ('verb4', models.CharField(default='Verb', max_length=200, null=True)),
                ('verb5', models.CharField(default='Verb', max_length=200, null=True)),
                ('SignOff', models.CharField(default='Name', max_length=200, null=True)),
            ],
        ),
    ]
