# Generated by Django 3.0.8 on 2020-08-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlydating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lower_age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='upper_age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
