# Generated by Django 3.0.8 on 2020-08-04 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import earlydating.puffin_functions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('earlydating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lower_age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preference',
            field=models.CharField(blank=True, choices=[('Male', 'M'), ('Female', 'F'), ('OTHER', 'OTHER')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'M'), ('Female', 'F'), ('OTHER', 'OTHER')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='upper_age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='/static/images/Proud_Puffin_default_user.jpg', null=True, upload_to='static/user_pixel', validators=[earlydating.puffin_functions.validate_file_size]),
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_vote', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'voter')},
            },
        ),
    ]
