# Generated by Django 3.0.8 on 2020-08-07 03:05

from django.db import migrations, models
import earlydating.puffin_functions


class Migration(migrations.Migration):

    dependencies = [
        ('earlydating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='SignOff',
            field=models.CharField(default='Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='activity',
            field=models.CharField(default='Activity', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='adjective1',
            field=models.CharField(default='Adjective', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='adjective2',
            field=models.CharField(default='Adjective', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='direction',
            field=models.CharField(default='Direction', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='exclamation',
            field=models.CharField(default='Exclamation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='greeting',
            field=models.CharField(default='Greeting', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='noun1',
            field=models.CharField(default='Noun', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='noun2',
            field=models.CharField(default='Noun', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='noun3',
            field=models.CharField(default='Noun', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='noun4',
            field=models.CharField(default='Noun', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='noun5',
            field=models.CharField(default='Pluralnoun', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='noun6',
            field=models.CharField(default='Pluralnoun', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pastverb',
            field=models.CharField(default='Pastverb', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verb0',
            field=models.CharField(default='Verb', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verb1',
            field=models.CharField(default='Verb', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verb2',
            field=models.CharField(default='Verb', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verb3',
            field=models.CharField(default='Verb', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verb4',
            field=models.CharField(default='Verb', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verb5',
            field=models.CharField(default='Verb', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='images/Proud_Puffin_default_user.jpg', null=True, upload_to='user_pixel', validators=[earlydating.puffin_functions.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='uservote',
            name='vote',
            field=models.BooleanField(default=False),
        ),
    ]
