# Generated by Django 3.0.8 on 2020-08-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlydating', '0002_auto_20200801_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
