# Generated by Django 3.0.8 on 2020-08-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlydating', '0003_auto_20200807_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='SignOff',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='adjective1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='adjective2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='exclamation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='greeting',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lower_age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='noun1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='noun2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='noun3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='noun4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='noun5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='noun6',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pastverb',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='upper_age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verb0',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verb1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verb2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verb3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verb4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verb5',
        ),
        migrations.AlterField(
            model_name='profile',
            name='preference',
            field=models.CharField(blank=True, choices=[('straight', 'straight'), ('gay', 'gay'), ('bisexual', 'bisexual')], max_length=10, null=True),
        ),
    ]
