# Generated by Django 3.0.8 on 2020-08-02 06:32

from django.db import migrations, models
import earlydating.pixel


class Migration(migrations.Migration):

    dependencies = [
        ('earlydating', '0003_auto_20200802_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(null=True, upload_to=earlydating.pixel.pixelate),
        ),
    ]
