# Generated by Django 3.0.8 on 2020-08-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlydating', '0003_auto_20200804_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='SignOff',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='adjective1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='adjective2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='exclamation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='greeting',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='noun1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='noun2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='noun3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='noun4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='noun5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='noun6',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pastverb',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verb0',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verb1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verb2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verb3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verb4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verb5',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
