# Generated by Django 3.0.8 on 2020-08-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earlydating', '0005_auto_20200802_1255'),
        ('earlydating', '0005_auto_20200802_2016'),
    ]

    operations = [
    ]
