# Generated by Django 3.0.8 on 2020-08-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlydating', '0007_auto_20200803_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/user_pixel'),
        ),
    ]
