# Generated by Django 3.0.3 on 2020-08-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nchan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['publication_date']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['publication_date']},
        ),
        migrations.RemoveField(
            model_name='anonymous',
            name='identifier',
        ),
    ]
