# Generated by Django 3.1 on 2020-08-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nchan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
