# Generated by Django 3.0.3 on 2020-08-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nchan', '0002_auto_20200804_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Anonymous',
        ),
    ]
