# Generated by Django 3.0.3 on 2020-08-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nchan', '0003_auto_20200804_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='board',
            name='id',
        ),
        migrations.RemoveField(
            model_name='board',
            name='post_num',
        ),
        migrations.AddField(
            model_name='board',
            name='board',
            field=models.CharField(default=0, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
